apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: weather
        image: chrimson/weatherapi
        ports:
        - containerPort: 8080
